from .BaseAnimator import * 
from .ImageAnimator import * 
from .DebugAnimator import * 
from .SpeedAnimator import * 
from .WaveAnimator import * 
from .FieldAnimator import * 
from .VelocityXAnimator import *
from .VelocityYAnimator import *
from .DivergenceAnimator import * 
from .CurlAnimator import * 
from .PressureAnimator import * 
